[tox]
envlist =
    lint,
    py310,
    py311,
    py312,
    py313,

# see https://python-poetry.org/docs/faq/#usecase-3
isolated_build = true

[testenv]
skip_install = true
allowlist_externals = poetry
# Poetry may not be in the path (e.g. if running in Jenkins)
# In that case, assume the location is in the POETRY environment variable
setenv =
    POETRY = {env:POETRY:poetry}
commands_pre = {env:POETRY} install
commands = {env:POETRY} run pytest --cov=email_decomposer --cov-report html --cov-report term --cov-report xml:coverage.xml

; [testenv:lint]
; commands =
;     {env:POETRY} run isort --version
;     {env:POETRY} run isort --check-only --df .
;     {env:POETRY} run black --version
;     {env:POETRY} run black --check --diff .
