version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build:
          matrix:
            parameters:
              python-version: ["3.10", "3.11", "3.12", "3.13"]
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-3.10
            - build-3.11
            - build-3.12
            - build-3.13
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  build:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "Makefile" }}-<< parameters.python-version >>
      - run:
          name: install python dependencies
          command: |
            make dev
      - save_cache:
          paths:
            - "~/.cache/pypoetry"
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "Makefile" }}-<< parameters.python-version >>
      - run:
          name: run tests
          command: |
            TOXENV="py$(echo << parameters.python-version >> | tr -d '.')"
            poetry run tox -e $TOXENV
            poetry run codecov
      - store_artifacts:
          path: htmlcov/
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "Makefile" }}-3.11
      - run:
          name: install python dependencies
          command: |
            make dev
      - save_cache:
          paths:
            - "~/.cache/pypoetry"
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "Makefile" }}-3.11
      - run:
          name: verify git tag vs. version
          command: |
            poetry version --short | grep -qx "$CIRCLE_TAG" || (echo "Git tag $CIRCLE_TAG does not match version $(poetry version --short)" && exit 1)
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD